[versions]
dropwizard-metrics = "4.2.0"
json = "20240303"

[libraries]
dropwizard-metrics-core = { group = "io.dropwizard.metrics", name = "metrics-core", version.ref = "dropwizard-metrics" }
json = { group = "org.json", name = "json", version.ref = "json" }